document.write( '<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n' );
document.write( '                <div class=\"col-xs-8 col-sm-8 col-md-8 col-lg-8\">\n' );
document.write( '                    <div class=\"menu\">\n' );
document.write( '                        <div class=\"col-md-12\">\n' );
document.write( '                            <ul>\n' );
document.write( '                                <li><a href=\"\">Tổng quan </a></li>\n' );
document.write( '                                <li><a href=\"\" class=\"current\">Quản lý KPI</a></li>\n' );
document.write( '                                <li><a href=\"\" >Marketing </a></li>\n' );
document.write( '                            </ul>\n' );
document.write( '                        </div>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '                <div class=\"col-xs-4 col-sm-4 col-md-4 col-lg-4\">\n' );
document.write( '                    <button class=\"btn btn-default user\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n' );
document.write( '                        <span class=\"username\">Nguyễn Văn A</span>\n' );
document.write( '                        <i class=\"fa fa-angle-down \"></i>\n' );
document.write( '                    </button>\n' );
document.write( '                    <ul class=\"user dropdown-menu\">\n' );
document.write( '                        <li>\n' );
document.write( '                            <span >\n' );
document.write( '                                <i class=\"fa fa-phone\"></i>\n' );
document.write( '                                <span> Hotline 1800 6751</span>\n' );
document.write( '                            </span>\n' );
document.write( '                        </li>\n' );
document.write( '                        <li>\n' );
document.write( '                            <span >\n' );
document.write( '                                <i class=\"fa fa-life-ring\"></i>\n' );
document.write( '                                <span> Đăng suất</span>\n' );
document.write( '                            </span>\n' );
document.write( '                        </li>\n' );
document.write( '                    </ul>\n' );
document.write( '                </div>\n' );
document.write( '        </nav>' );
